### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by jbkunst** [Elizemiku/Interactive-Graphics#1]
Hi @Elizemiku 

Thanks for this. I'll take some time to see if I come with some improvements for highcharter ;)!.

Thanks again.

**Comment by Elizemiku** [comment]
Hi @jbkunst. You're welcome :) . I'm studying R some time ago. I like to do interactive graphics, so I started compare the packages that use this.  Thanks for the attention and the package highcharter!

**Comment by Elizemiku** [comment]
I guess that we can close this issue now, thanks to improvements with regression graphs.
